//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Cine
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cine()
    {
        this.CinePelicula = new HashSet<CinePelicula>();
    }

    public int IdCine { get; set; }
    public string nombre { get; set; }
    public int idCiudad { get; set; }

    public virtual Ciudad Ciudad { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CinePelicula> CinePelicula { get; set; }
}

public partial class CinePelicula
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CinePelicula()
    {
        this.Horario = new HashSet<Horario>();
    }

    public int IdCinePelicula { get; set; }
    public int idCine { get; set; }
    public int idPelicula { get; set; }

    public virtual Cine Cine { get; set; }
    public virtual Pelicula Pelicula { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Horario> Horario { get; set; }
}

public partial class Ciudad
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ciudad()
    {
        this.Cine = new HashSet<Cine>();
    }

    public int IdCiudad { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cine> Cine { get; set; }
}

public partial class Horario
{
    public int IdCinePelicula { get; set; }
    public string horario1 { get; set; }

    public virtual CinePelicula CinePelicula { get; set; }
}

public partial class Pelicula
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pelicula()
    {
        this.CinePelicula = new HashSet<CinePelicula>();
    }

    public int IdPelicula { get; set; }
    public string titulo { get; set; }
    public string clasificacion { get; set; }
    public int duracion { get; set; }
    public string archivoImg { get; set; }
    public string sinposis { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CinePelicula> CinePelicula { get; set; }
}
